spring:
  application:
    name: springcloud_gw_simple
  profiles:
    active: local
  banner:
    location: "classpath:config/app-banner.txt"
app-info:
  build:
    version: '0.0.1-SNAPSHOT'
    timestamp: '@app.build.timestamp@'